### ISSUE TITLE
Все заявки. Изменение.

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#100]
1) Изменить статус - кнопка активна, хотя заявка не выбрана! При нажатии выдает ошибку
2) Убираем вкладку "Заявки в работе". Кнопки с неё переносим на вкладку "Все заявки". Саму вкладку переименовываем в "Заявки".
3) Добавляем кнопку "Настройка", в ней  "Настроить столбцы" (Аккордеон), где можно выбрать столбцы, которые юзер хочет увидеть и аккордеон "Фильтрация" - Здесь появляются 2 кнопки - "Показать все" и "Диапазон дат" - мы выбираем либо все заявки сразу, либо с датой отправки между датой А и датой Б. За ними идут строки с названиями полей слева и инпутами/выпадающими списками/выбором дат справа. В конце - кнопка "Поиск", после чего в таблице появляются данные по всем этим фильтрам.
4) Добавить фильтры в колонки
5) Кнопка "Показать все" - зачем нужна? (я забыла:))
6) Закрепить заголовки таблицы!
7) Саму таблицу оформить как у Энергомикса (стиль)

**Comment by iSosnitsky** [comment]
![screenshot 2019-01-31 at 17 57 30](https://user-images.githubusercontent.com/10558886/52062518-b63d7280-2581-11e9-8f2e-17541feeb95a.png)
