### ISSUE TITLE
Порядок перехода. Изменение названий. Диспетчер.

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#101]
1. После регистрации - переходим на вкладку "Профиль" в Настройках.
2. После авторизации - переходим на Дашборд.
3. Переименовать "Заявки" в "Рабочий стол".
4. Из "Настроек" в "Рабочий стол" перенести всё, кроме Профиля, Пункта, Пользователей.
5. Переименовать "Ревью" в "Котировки" (в маршрутах кнопку "Отправить на ревью" тоже переименовать в "Запросить котировки")
6. "На карте" переименовать в "Карта"

**Comment by iSosnitsky** [comment]
1 и 2 - При регистрации записать в сессию действие регистрации, если оно есть - перекинуть в профиль. Иначе - в дашборд.

**Comment by iSosnitsky** [comment]
Пока дашборд спрятан - после авторизации, если юзер принял сообщение о куках - перекидываю его в заявки.

**Comment by ysmirnova87** [comment]
Дашборд вроде только у перевозчика прятали. Почему-то он у диспетчера тоже исчез.


>Понедельник, 21 января 2019, 5:08 +03:00 от Roman Kurbanov <notifications@github.com>:
>
>Пока дашборд спрятан - после авторизации, если юзер принял сообщение о куках - перекидываю его в заявки.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юлия Смирнова
