### ISSUE TITLE
Создание маршрута. Косметика.

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#102]
При создании маршрута скрыть все стоимости, кроме первой (открывать по нажатию на кнопку "Дополнительная тарификация")

**Comment by iSosnitsky** [comment]
![screenshot 2019-01-15 at 11 32 51](https://user-images.githubusercontent.com/10558886/51168099-21bcea00-18ca-11e9-8c17-47a9eb99dde7.png)
![screenshot 2019-01-15 at 11 32 56](https://user-images.githubusercontent.com/10558886/51168103-24b7da80-18ca-11e9-9ecb-ae8a011fe51b.png)
