### ISSUE TITLE
Переделать регистрацию

### ISSUE THREAD

**Issue by iSosnitsky** [iSosnitsky/DschinghisKhan#82]
1. Убрать "Полное название компании"  (Берется из dadata по ИНН)
2. На странице регистрации добавить ссылку на авторизацию (кнопка "Войти")
3. После регистрации не перебрасывает в систему, остаюсь на той же странице
4. E-mail или телефон - одно из полей обязательно (выбор: регистрация по e-mail/телефону)
5.  Убрать текст "После регистрации можно будет создать нескольких пользователей" 
6. Пароль. Убрать подпись "не менее 6 символов", сделать аналогично телеграм - высылаем код активации для устройства и далее сохраняем для этого устройства.
7. Убрать адрес склада на этапе регистрации. В "Основной склад отправки" добавить в заполняемое поле текст "Название пункта и его адрес"
8. После регистрации перебрасывать на страницу с перевозчиками.

**Comment by ysmirnova87** [comment]
1) После регистрации в карточке организации выделять красным подчеркиванием поля, данные в которые не были подставлены из дадата автоматически.
2) В смс или на email отправлять не только пароль, но и логин
3) По оформлению, нужно слово "или" между email и телефоном. Ограничение email сколько символов сейчас?
![image](https://user-images.githubusercontent.com/30569268/49736963-946bf180-fc9c-11e8-8bf4-07e5f2035527.png)

**Comment by ysmirnova87** [comment]
Случайно закрыла:)

**Comment by iSosnitsky** [comment]
>Ограничение email сколько символов сейчас?
64 Символа.
Но вообще, можно просто форму шире сделать

**Comment by iSosnitsky** [comment]
>По оформлению, нужно слово "или" между email и телефоном. 

![screenshot 2018-12-10 at 18 44 50](https://user-images.githubusercontent.com/10558886/49743441-c46ec100-fcab-11e8-9ea4-050241e5ba20.png)

**Comment by ysmirnova87** [comment]
1. При вставке скопированного номера из 11 цифр, первые +7 или 8 вырезаются (сейчас убирается последняя цифра, это неправильно!)
2. Убрать подсказки (серый текст) из всех полей, кроме Основного склада отправки. Там текст заменить на "Например, "РЦ Рязань""
3. Слово "Или" сделать заглавными буквами и расположить по центру.
4. Синий цвет сделать насыщенно синим (как в подчеркивании), буквы также сделать не черными, а тёмно-синими.

**Comment by ysmirnova87** [comment]
После регистрации перебрасывать на страницу с данными о компании, а не на страницу с перевозчиками.

**Comment by ysmirnova87** [comment]
При попытке повторной регистрации с тем же ИНН выскакивает ошибка:
Компания с таким ИНН уже существует (ФГУП "ПОЧТА РОССИИ"/smirnovayi@logicsmart.ru)
Надо убрать из текста ошибки указание на эл.почту, вместо этого выводить:
Компания с таким ИНН уже существует (ФГУП "ПОЧТА РОССИИ"). Свяжитесь с администратором info@logicsmart.ru

**Comment by iSosnitsky** [comment]
![screenshot 2019-01-02 at 08 03 37](https://user-images.githubusercontent.com/10558886/50579217-f0bdcd80-0e64-11e9-8e96-b849dd96e602.png)
