### ISSUE TITLE
Добавление нового пользователя

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#89]
Разделить "Имя" на Фамилию,   Имя, Отчество, при этом обязательно только поле Имя (пометить звёздочкой)
Пароль вводить два раза, проверять, чтобы пароли совпадали.
При вводе логина проверять его наличие в   базе! Или у нас есть связка логин-компания? Тогда для компании логин уникальный?

**Comment by iSosnitsky** [comment]
> При вводе логина проверять его наличие в базе! Или у нас есть связка логин-компания? Тогда для компании логин уникальный?

Нет, логин уникальный среди всех пользователей, не только для пользователей одной компании.

**Comment by iSosnitsky** [comment]
>Разделить "Имя" на Фамилию, Имя, Отчество, при этом обязательно только поле Имя (пометить звёздочкой)
Могу разделить ФИО на 3 части при создании, а при редактировании - чтобы редактировалось как целое. Таким образом, не придется разделять одно поле в базе данных на три.
Можно сделать раздельным и при редактировании, но тогда придется плодить поля в базе данных.
