### ISSUE TITLE
Профиль. Косметика.

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#91]
Разделить профиль и склады отправки по разным вкладкам.
Выделенное серым - запретить редактировать (как логин).
Подсвечивать красной полоской незаполненные данные.
Вместо "Обновить" - везде "Сохранить".
Остальное - на скриншотах.
![default](https://user-images.githubusercontent.com/30569268/50423738-5230db80-086a-11e9-86b7-270def8cbda1.png)
![-](https://user-images.githubusercontent.com/30569268/50423739-5230db80-086a-11e9-849a-4c19a0a742c1.png)

**Comment by iSosnitsky** [comment]
>Разделить профиль и склады отправки по разным вкладкам.

Это для основного склада отправки сделать отдельную вкладку?

**Comment by ysmirnova87** [comment]
Да


>Пятница, 28 декабря 2018, 14:16 +03:00 от Roman Kurbanov <notifications@github.com>:
>
>>Разделить профиль и склады отправки по разным вкладкам.
>Это для основного склада отправки сделать отдельную вкладку?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Юлия Смирнова

**Comment by iSosnitsky** [comment]
Убрал основной склад отправки на отдельную вкладку, теперь Контакт снизу страницы один как перст. Попробовал перенести его наверх - стало неясно, какие поля к чему принадлежат. Попробовал объединить их карточками: 
![screenshot 2018-12-28 at 23 46 43](https://user-images.githubusercontent.com/10558886/50525036-f0d36b80-0afa-11e9-90c9-fef81bf74727.png)

**Comment by iSosnitsky** [comment]
Еще для наглядности попробовал белый фон убрать:
![screenshot 2018-12-28 at 23 48 47](https://user-images.githubusercontent.com/10558886/50525097-31cb8000-0afb-11e9-86cc-3f645c8d885e.png)
