### ISSUE TITLE
Переделываем страницу с клиентами (фронт)

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#93]
Инфо в мокапах
![_1 1](https://user-images.githubusercontent.com/30569268/51032909-b7970300-15b2-11e9-9a97-ef453fa18acc.png)
![_1 2](https://user-images.githubusercontent.com/30569268/51032910-b7970300-15b2-11e9-91aa-7188269d8639.png)

![_1 3](https://user-images.githubusercontent.com/30569268/51033246-cc27cb00-15b3-11e9-80e7-5031347fcdfc.png)

**Comment by iSosnitsky** [comment]
В пунктах доставки - дополнение к документам - что это за поле? Текстовое? Файл?

**Comment by ysmirnova87** [comment]
Длинное текстовое
