### ISSUE TITLE
Ввод транспортных средств (справочник перевозчика)

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#96]
1) Переименовать "Номер" на "Гос. номер"
2) Добавить поле "Модель", в ней - выпадающий список (данные для списка приложу в комментарии к этой задаче)
3) Если выбран тип "Тягач", то скрываем все поля, кроме "Комментарий", "Гос.номер" и "Модель"

**Comment by iSosnitsky** [comment]
Что нужно в "Модели"?

**Comment by ysmirnova87** [comment]
ГАЗ
ЗИЛ
КАМАЗ
МАЗ
ПИНГО-АВТО
СПЕКТР-АВТО
ЦТТМ
AVIA
BAW
DAF
FORD
FOTON
HINO
HYUNDAI
ISUZU
IVECO
JAC
MAN
MERCEDES
MITSUBISHI FUSO
NAVECO
RENAULT
SCANIA
TATA DAEWOO
VOLKSWAGEN
VOLVO
