### ISSUE TITLE
Принятие заявки перевозчиком

### ISSUE THREAD

**Issue by ysmirnova87** [iSosnitsky/DschinghisKhan#97]
Когда перевозчик воодит данные о ТС, должна быть возможность ввести несколько ТС (основное и дополнительные).

**Comment by iSosnitsky** [comment]
Сделать одно ТС основным и сколь угодно дополнительных - отдельным полем.

**Comment by iSosnitsky** [comment]
То же самое с водителями.

**Comment by iSosnitsky** [comment]
![screenshot 2019-01-15 at 14 38 46](https://user-images.githubusercontent.com/10558886/51178372-626d3100-18d3-11e9-8963-0f880492734c.png)
![Uploading Screenshot 2019-01-15 at 14.24.34.png…]()
![Uploading Screenshot 2019-01-15 at 14.24.14.png…]()

**Comment by iSosnitsky** [comment]
В таблицу доп. водители/транспорт добавлю после #100
